name: repo_analyzer
description: A CLI tool to analyze git change entropy
version: 0.0.5
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.9.2

# Add regular dependencies here.
dependencies:
  args: ^2.7.0
  glob: ^2.1.3
  mason_logger: ^0.3.3
  path: ^1.9.0
  process_run: ^1.2.4

dev_dependencies:
  lints: ^6.0.0
  test: ^1.25.0

executables:
  rea: main